# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mail', 'mail'), ('jabber', 'jabber')], max_length=8)),
                ('recipient', models.CharField(max_length=1024)),
                ('periodicity', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('next_refresh_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_snapshot', models.TextField(blank=True, default='')),
                ('last_status_code', models.DecimalField(decimal_places=0, default=200, max_digits=3)),
            ],
        ),
    ]
